package com.example.internshipfinal.status;

public enum SignupStatus {

    INCORRECT_FIRSTNAME_TOO_SHORT,
    INCORRECT_FIRSTNAME_TOO_LONG,
    INCORRECT_ID_EXISTS,
    INCORRECT_NAME_CHARACTERS,
    INCORRECT_LASTNAME_TOO_SHORT,
    INCORRECT_LASTNAME_TOO_LONG,
    INCORRECT_LASTNAME_CHARACTERS,
    INCORRECT_ID_LENGTH_TOO_SHORT,
    INCORRECT_ID_LENGTH_TOO_LONG,
    INCORRECT_ID_CHARACTERS,
    INCORRECT_USERNAME_TOO_SHORT,
    INCORRECT_USERNAME_TOO_LONG,
    INCORRECT_USERNAME_CHARACTERS,
    INCORRECT_USERNAME_EXISTS,
    INCORRECT_PASSWORD_TOO_SHORT,
    INCORRECT_PASSWORD_TOO_LONG,
    INCORRECT_PASSWORD_CHARACTERS,
    INCORRECT_PASSWORD_MUST_USE_CHARACTERS_NOT_USED,
    SIGNED_UP_SUCCESSFULLY

}
